---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    transport:
      name: winrm
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb

suites:
  - name: server-community
    run_list:
      - recipe[minitest-handler]
      - recipe[sync-gateway::default]
    attributes: {}
